server:
 port: 8081
spring:
 security:
   oauth2:
     client:
       registration:
         keycloak:
           client-id: springboot
           client-secret: HKdG1MHdZ4fgQ1hyMSG8lDx0x9hr8bUn
           provider: keycloak
           scope: openid
           authorization-grant-type: authorization_code
           redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
       provider:
         keycloak:
           authorization-uri: http://localhost:8080/realms/keycloak-demo/protocol/openid-connect/auth
           token-uri: http://localhost:8080/realms/keycloak-demo/protocol/openid-connect/token
           user-info-uri: http://localhost:8080/realms/keycloak-demo/protocol/openid-connect/userinfo
           jwk-set-uri: http://localhost:8080/realms/keycloak-demo/protocol/openid-connect/certs
           user-name-attribute: preferred_username